---
config:
  layout: elk
---
flowchart TB
 subgraph subGraph0["Site A: Samoa"]
        A_SW2["Switch 2 (VTEP)"]
        A_SW1["Switch 1 (VTEP)"]
        A_RS1["Route Server 1"]
        A_RS2["Route Server 2"]
        Member_A1["ISP A"]
        Member_A2["Gov Net"]
  end
 subgraph subGraph1["Site B: Fiji"]
        B_SW2["Switch 2 (VTEP)"]
        B_SW1["Switch 1 (VTEP)"]
        B_RS1["Route Server 1"]
        B_RS2["Route Server 2"]
        Member_B1["ISP B"]
        Member_B2["University"]
  end
    A_SW1 --- A_SW2
    A_RS1 --- A_SW1
    A_RS2 --- A_SW2
    Member_A1 --- A_SW1
    Member_A2 --- A_SW2
    B_SW1 --- B_SW2
    B_RS1 --- B_SW1
    B_RS2 --- B_SW2
    Member_B1 --- B_SW1
    Member_B2 --- B_SW2
    A_SW1 -. VXLAN Tunnel .-> B_SW1
    A_SW2 -. VXLAN Tunnel .-> B_SW2
    A_SW1 -. IBGP EVPN .-> A_SW2
    B_SW1 -. IBGP EVPN .-> B_SW2
